version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: postgres-sofico
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: benfica15
      POSTGRES_DB: sofico_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./sofico-backend
    container_name: backend-sofico
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - postgres

volumes:
  postgres-data:
